//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobHub.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
<<<<<<< HEAD
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
=======
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
>>>>>>> 07d58633f3a8301a2bce7631e74ed3454f76d3e7
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-742LD2D;Initial Catalog=JobWin;Integrated Security=True;Encry" +
            "pt=False;Encrypt=False;MultipleActiveResultSets=True;")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TU;Initial Catalog=JobHub;Integrated Security=True;Encrypt=False;Mult" +
            "ipleActiveResultSets=True;")]
>>>>>>> 07d58633f3a8301a2bce7631e74ed3454f76d3e7
        public string conn {
            get {
                return ((string)(this["conn"]));
            }
        }
    }
}
